### ISSUE TITLE
Gitbook

### ISSUE THREAD

**Issue by piranna** [oslugr/asignaturas-liberadas#1]
What about using Gitbook format for the lessons and the practices?

**Comment by JJ** [comment]
Este repositorio es solamente para que pongan un enlace a sus asignaturas. En todo caso, en vez de GitBook yo uso markdown directamente.

**Comment by piranna** [comment]
Pense que estaría aquí alojado también el contenido. Markdown esta (muy) bien, aunque si con un esfuerzo extra se consigue que el formateo quede chulo como es con el caso de Gitbook, pues mejor :-D

**Comment by JJ** [comment]
Ya quisiera siquiera que liberaran algún contenido. Que además lo alojen en GitHub es una utopía... En markdown quedan también bastante chulos, puedes exportarlos a epub o generar una página con Jekyll

**Comment by piranna** [comment]
Markdown en github queda genial :-) Es solo que añadiendo un par de archivos mas y dejando el markdown con una jerarquia concreta, te consigues un libro y una pagina web de gratis :-D Es lo que hice con mi [pfc](https://github.com/piranna/pfc), y ademas tenia control de versiones y edición multiusuario online... :-P
